In [13]:
#import libraries to webscrape and save data as csv
import requests
from bs4 import BeautifulSoup
import csv

#create a list of urls to scrape
urls = ['https://www.indeed.com/jobs?q=data+scientist&l=New+York%2C+NY','https://www.indeed.com/jobs?q=data+analyst+entry+level&l=New+York%2C+NY']

#create a list to store the data
data = []

#loop through the urls
for url in urls:
    #make a request to the url
    response = requests.get(url)
    #parse the html
    soup = BeautifulSoup(response.text, 'html.parser')
    #find the job listings
    job_listings = soup.find_all('div', class_='job_seen_beacon')
    #loop through the job listings
    for job_listing in job_listings:
        #create a dictionary to store the data
        job_data = {}
        #find the title
        title = job_listing.find('h2', class_='jobTitle')
        #add the title to the dictionary
        job_data['title'] = title.text
        #find the company
        company = job_listing.find('span', class_='companyName')
        #add the company to the dictionary
        job_data['company'] = company.text
        #add the dictionary to the data list
        data.append(job_data)

#create a csv file to store the data
with open('indeed_data.csv', 'w') as csvfile:
    #create the csv writer object
    csvwriter = csv.writer(csvfile)
    #write the header
    csvwriter.writerow(['title', 'company'])
    #write the data
    for job in data:
        csvwriter.writerow([job['title'], job['company']])

#print the data
print(data)

[{'title': 'newJunior Data Scientist Apprentice', 'company': 'IBM'}, {'title': 'Data Scientist, Game Analytics & Strategy', 'company': 'the NBA'}, {'title': 'Junior Data Scientist (NYC or Remote)', 'company': 'ViacomCBS'}, {'title': 'Data Scientist, TikTok Creation and Consumption', 'company': 'TikTok'}, {'title': 'Associate Data Scientist, User Fraud', 'company': 'Spotify'}, {'title': 'Entry Level - Associate Data Scientist (Commercial)', 'company': 'IBM'}, {'title': 'newFull Stack Data Scientist - NLP', 'company': 'Amex'}, {'title': 'newJunior Data Scientist - BAM Elevate', 'company': 'Balyasny'}, {'title': 'newData Scientist/ Data Analytics Associate - STEM iDEAS Rotati...', 'company': 'Cepheid'}, {'title': 'Data Scientist - New York or North Carolina', 'company': 'IBM'}, {'title': 'newEconomic Data Scientist', 'company': 'NYC Careers'}, {'title': 'newData Scientist', 'company': 'Northwell Health'}, {'title': 'Data Scientist', 'company': 'Source Enterprises'}, {'title': 'newData Scientist', 'company': 'Frontier Communications'}, {'title': 'Data Scientist', 'company': 'Pfizer'}, {'title': 'newJunior Data Analyst', 'company': 'MealPal'}, {'title': 'Product Analyst/Data Scientist', 'company': 'Salesforce'}, {'title': 'Data & Credit Analyst', 'company': 'Reorg Research'}, {'title': 'Marketing Analytics Analyst', 'company': 'Kepler Group'}, {'title': 'Entry Level - Financial Research Analyst', 'company': 'IHS Markit'}, {'title': 'Business Analyst; Pharmacy; Mount Sinai Health System', 'company': 'Mount Sinai'}, {'title': 'Marketing Data Analyst', 'company': 'Veeva Systems'}, {'title': 'newBusiness Analysis Associate (Hybrid role)', 'company': 'Prudential'}, {'title': '2022 Technology Analyst Program: Infrastructure, Security, D...', 'company': 'Fiserv, Inc.'}, {'title': 'Business Analyst', 'company': 'Neuberger Berman'}, {'title': 'Financial Market Info & Data Analytics Associate - Summer/Fa...', 'company': 'PRICE WATERHOUSE COOPERS'}, {'title': 'Program Analyst - Corporate/HR/Business Analyst', 'company': 'Fiserv, Inc.'}, {'title': 'newProduct Analyst, Private Markets', 'company': 'IHS Markit'}, {'title': 'newReps & Warranties Analyst', 'company': 'Aon'}, {'title': 'Health Benefits Data Analyst, Pharmacy Benefits Informatics', 'company': 'The Segal Group, Inc.'}]

In [14]:
import pandas as pd
df = pd.read_csv('indeed_data.csv')

In [15]:
df

,title,company
0,newJunior Data Scientist Apprentice,IBM
1,"Data Scientist, Game Analytics & Strategy",the NBA
2,Junior Data Scientist (NYC or Remote),ViacomCBS
3,"Data Scientist, TikTok Creation and Consumption",TikTok
4,"Associate Data Scientist, User Fraud",Spotify
5,Entry Level - Associate Data Scientist (Commer...,IBM
6,newFull Stack Data Scientist - NLP,Amex
7,newJunior Data Scientist - BAM Elevate,Balyasny
8,newData Scientist/ Data Analytics Associate - ...,Cepheid
9,Data Scientist - New York or North Carolina,IBM
10,newEconomic Data Scientist,NYC Careers
11,newData Scientist,Northwell Health
12,Data Scientist,Source Enterprises
13,newData Scientist,Frontier Communications
14,Data Scientist,Pfizer
15,newJunior Data Analyst,MealPal
16,Product Analyst/Data Scientist,Salesforce
17,Data & Credit Analyst,Reorg Research
18,Marketing Analytics Analyst,Kepler Group
19,Entry Level - Financial Research Analyst,IHS Markit
20,Business Analyst; Pharmacy; Mount Sinai Health...,Mount Sinai
21,Marketing Data Analyst,Veeva Systems
22,newBusiness Analysis Associate (Hybrid role),Prudential
23,2022 Technology Analyst Program: Infrastructur...,"Fiserv, Inc."
24,Business Analyst,Neuberger Berman
25,Financial Market Info & Data Analytics Associa...,PRICE WATERHOUSE COOPERS
26,Program Analyst - Corporate/HR/Business Analyst,"Fiserv, Inc."
27,"newProduct Analyst, Private Markets",IHS Markit
28,newReps & Warranties Analyst,Aon
29,"Health Benefits Data Analyst, Pharmacy Benefit...","The Segal Group, Inc."